#!/usr/bin/env python3
"""
extract_gamedata.py -- regenerate gamedata.py from the built game images.

WHY THIS EXISTS. mapfix decides "will this entity actually spawn?" by asking
the same three questions G_CallSpawn asks, in the same order (g_spawn.cpp):

    1. G_ItemForEntity()          -- is the classname a gs_items entry?
    2. G_asCallMapEntitySpawnScript() -- does a LOADED AngelScript section
                                         define `void <classname>( Entity@ )`?
    3. the static spawns[] table  -- Q_stricmp, so CASE-INSENSITIVE.

Answering that from memory is how you ship a "fixer" that deletes entities the
engine would have spawned fine. So the three tables are extracted from the real
artifacts instead:

    spawns[]        <- source/game/g_spawn.cpp        (racesow-gamemod:build)
    gs_items        <- source/gameshared/gs_items.c   (racesow-gamemod:build)
    AS spawn funcs  <- the .as sections the racemod actually LOADS, read out of
                       racemod/hrace.pk3 + basewsw/data0_21pure.pk3 in the
                       game image

Note the case asymmetry, which is not a detail: native lookups use Q_stricmp,
but the AngelScript lookup is an exact function-name match. That is why the
racemod carries both `target_stoptimer` and `target_stopTimer` -- see the
comment in hrace/entities/timers.as. mapfix reproduces the asymmetry exactly.

Usage:
    tools/mapfix/extract_gamedata.py [--game-image IMG] [--build-image IMG]
                                     [-o tools/mapfix/gamedata.py]

Requires docker and the two locally-built images. Re-run it after an engine or
racemod change that adds or removes an entity spawn function.
"""
import argparse
import os
import re
import subprocess
import sys
import tempfile
import zipfile

# The gametype .gt lists the sections it loads; but the load order (and the
# generic/legacy sections the engine pulls in for every gametype) is only
# visible in the boot log. This is that list, as printed by
# `warsow-race:* +map <any>` under "* Loaded script section".
LOADED_PREFIXES = (
    "progs/shared/",
    "progs/gametypes/generic/",
    "progs/gametypes/legacy/",
    "progs/gametypes/hrace/",
)
LOADED_EXACT = ("progs/gametypes/hrace.as",)

# `void <name>( Entity@ ent )` -- the one signature G_asCallMapEntitySpawnScript
# will bind to. Anything else in the file is an ordinary helper, not a spawn.
AS_SPAWN_RE = re.compile(
    r"^\s*void\s+([A-Za-z_][A-Za-z_0-9]*)\s*\(\s*(?:const\s+)?Entity\s*@?\s*&?\s*"
    r"[A-Za-z_][A-Za-z_0-9]*\s*\)\s*$",
    re.M,
)


def docker_cp(image, src, dst):
    cid = subprocess.check_output(["docker", "create", image], text=True).strip()
    try:
        subprocess.check_call(["docker", "cp", f"{cid}:{src}", dst],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    finally:
        subprocess.call(["docker", "rm", cid], stdout=subprocess.DEVNULL)


def native_spawns(g_spawn_cpp):
    src = open(g_spawn_cpp, encoding="latin-1").read()
    m = re.search(r"spawn_t\s+spawns\[\]\s*=\s*\{(.*?)\n\};", src, re.S)
    if not m:
        sys.exit("FATAL: could not locate spawns[] in g_spawn.cpp")
    names = re.findall(r'\{\s*"([A-Za-z_0-9]+)"', m.group(1))
    if len(names) < 40:
        sys.exit(f"FATAL: spawns[] yielded only {len(names)} names -- parse is wrong")
    return sorted(set(names))


def item_classnames(gs_items_c):
    src = open(gs_items_c, encoding="latin-1").read()
    names = re.findall(r'"((?:item|weapon|ammo)_[A-Za-z_0-9]+)"', src)
    if len(names) < 20:
        sys.exit(f"FATAL: gs_items.c yielded only {len(names)} names -- parse is wrong")
    return sorted(set(names))


def as_spawns(pk3s):
    found, sections = set(), []
    for pk3 in pk3s:
        with zipfile.ZipFile(pk3) as z:
            for name in z.namelist():
                if not name.endswith(".as"):
                    continue
                if not (name.startswith(LOADED_PREFIXES) or name in LOADED_EXACT):
                    continue
                sections.append(name)
                found.update(AS_SPAWN_RE.findall(z.read(name).decode("latin-1")))
    if not sections:
        sys.exit("FATAL: no loaded .as sections found in the given pk3s")
    return sorted(found), sorted(set(sections))


HEADER = '''\
"""
gamedata.py -- GENERATED by extract_gamedata.py. Do not hand-edit.

The three tables G_CallSpawn consults, lifted from the built artifacts. See
extract_gamedata.py for provenance and for why the case handling differs
between NATIVE_SPAWNS/ITEM_CLASSNAMES (Q_stricmp -> case-insensitive) and
AS_SPAWNS (exact AngelScript function-name match -> case-sensitive).

Source images: {game_image} (scripts), {build_image} (engine source).
"""

'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--game-image", default="warsow-race:crossfollow")
    ap.add_argument("--build-image", default="racesow-gamemod:build")
    ap.add_argument("-o", "--out",
                    default=os.path.join(os.path.dirname(__file__), "gamedata.py"))
    a = ap.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        docker_cp(a.build_image, "/build/repo/source/game/g_spawn.cpp", tmp)
        docker_cp(a.build_image, "/build/repo/source/gameshared/gs_items.c", tmp)
        docker_cp(a.game_image, "/warsow/racemod/hrace.pk3", tmp)
        docker_cp(a.game_image, "/warsow/basewsw/data0_21pure.pk3", tmp)
        for f in ("g_spawn.cpp", "gs_items.c", "hrace.pk3", "data0_21pure.pk3"):
            if not os.path.exists(os.path.join(tmp, f)):
                sys.exit(f"FATAL: {f} did not come out of the image")
        native = native_spawns(os.path.join(tmp, "g_spawn.cpp"))
        items = item_classnames(os.path.join(tmp, "gs_items.c"))
        asf, sections = as_spawns([os.path.join(tmp, "hrace.pk3"),
                                   os.path.join(tmp, "data0_21pure.pk3")])

    def block(name, values, comment):
        out = [f"# {comment}", f"{name} = frozenset(("]
        out += [f'    "{v}",' for v in values]
        out += ["))", ""]
        return "\n".join(out)

    with open(a.out, "w", encoding="utf-8") as f:
        f.write(HEADER.format(game_image=a.game_image, build_image=a.build_image))
        f.write(block("NATIVE_SPAWNS", native,
                      "g_spawn.cpp spawns[] -- matched with Q_stricmp (case-insensitive)."))
        f.write("\n")
        f.write(block("ITEM_CLASSNAMES", items,
                      "gs_items.c -- G_ItemForEntity runs BEFORE everything else, case-insensitive."))
        f.write("\n")
        f.write(block("AS_SPAWNS", asf,
                      "void <name>( Entity@ ) in a LOADED racemod section -- EXACT case match."))
        f.write("\n# The .as sections the racemod loads at boot, for the record:\n")
        f.write("AS_SECTIONS = (\n")
        for s in sections:
            f.write(f'    "{s}",\n')
        f.write(")\n")
    print(f"wrote {a.out}: {len(native)} native, {len(items)} items, "
          f"{len(asf)} AS spawns from {len(sections)} sections")


if __name__ == "__main__":
    main()
