-- Ops surface for the admin area: per-server RCON, a server log stream, and the
-- maintenance-mode broadcast. Three small additions land together because the
-- admin "servers" page ties them into one operator console.
--
--   * server.rcon_password — the plaintext RCON password the web app needs to
--     send connectionless `rcon <pass> <cmd>` UDP packets to a game server (the
--     same host:port the live poller already queries via `address`). RCON is a
--     cleartext protocol, so the secret MUST be stored recoverably; it is only
--     ever read by the admin routes / CLI and is never exposed by servers() or
--     any public API. Set it with `node admin.js rcon <id> <password|->`. NULL =
--     RCON not configured for that server (it is skipped by broadcasts).
--
--   * server_log — a capped stream of operator-visible lines shown at
--     /admin/logs. Three producers write here:
--       source='console'     — a game server's shipped stdout (POST /api/ingest/log)
--       source='event'       — the web app's own per-server activity (ingest, /flag, …)
--       source='rcon'|'maintenance' — admin actions (broadcasts, console commands)
--     Pruned to the newest LOG_KEEP rows (server.js) so it can never grow without
--     bound. server_id is NULLable + ON DELETE SET NULL so a deleted/unknown
--     server's lines survive as orphaned context rather than cascading away.
--
--   * maintenance state lives in the existing key/value `config` table (keys
--     maintenance_active / maintenance_since / maintenance_message /
--     maintenance_by / maintenance_rebroadcast_at), so no schema is needed for it.
--
-- Timestamps are UNIX seconds (BIGINT), matching every other table here.

-- Up Migration
ALTER TABLE server ADD COLUMN IF NOT EXISTS rcon_password TEXT;

CREATE TABLE IF NOT EXISTS server_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id  BIGINT REFERENCES server(id) ON DELETE SET NULL ON UPDATE CASCADE,
  source     TEXT NOT NULL,            -- console|event|rcon|maintenance|system
  level      TEXT,                     -- info|warn|error (best-effort, parsed from console tags)
  line       TEXT NOT NULL,
  created_at BIGINT NOT NULL
);
-- Newest-first tails (the /admin/logs default) and per-server / per-source
-- filters are all index-backed; id DESC is the natural recency order.
CREATE INDEX IF NOT EXISTS idx_server_log_id     ON server_log(id DESC);
CREATE INDEX IF NOT EXISTS idx_server_log_server ON server_log(server_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_server_log_source ON server_log(source, id DESC);

-- Down Migration
DROP TABLE IF EXISTS server_log CASCADE;
ALTER TABLE server DROP COLUMN IF EXISTS rcon_password;
