-- The meta map's seed board.
--
-- random_map is a course that does not exist until a server deals it: hrace's
-- dealer (server/racemod/.../hrace/metamap.as) builds a route out of compiled
-- tiles from a seed, and every player on that server races the same route. A
-- time set there is NOT a record and deliberately never reaches `race`,
-- `finish`, `run_tally` or any map leaderboard — the course was invented a
-- minute earlier, so comparing a time on it to a time on any other course, or
-- to a time on a different seed, is meaningless.
--
-- What IS meaningful is the PAIR: the time, and the seed that produced the
-- route it was set on. That is the whole reason this table exists separately
-- rather than as a flag on `race`. Anyone reading a row can type `seed <n>`
-- in game, get the identical course, and race the same run.
--
-- Notes worth keeping next to the schema:
--
--   * there is no map_id. random_map is one name covering an unbounded family
--     of courses; a map row for it would collect rows from thousands of
--     different courses under one leaderboard, which is exactly the confusion
--     this table exists to avoid.
--
--   * player_id is the CANONICAL representative at insert time, the same
--     convention as duel and tournament_entrant. Reads must map through
--     canonical_id rather than comparing raw ids, because a canonical rebuild
--     can pick a new representative for an alias group.
--
--   * pieces / route_units describe the course the time was set on. Seeds do
--     not all produce routes of the same length (a route that folds itself
--     into a corner ends early, by design), so a board that showed times alone
--     would rank a short course above a long one and look broken.
--
--   * (seed, player_id) is UNIQUE and keeps only the player's BEST time on
--     that seed, which is what makes a seed's rows a race between people
--     rather than a log of attempts.

-- Up Migration
CREATE TABLE IF NOT EXISTS random_run (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seed         BIGINT  NOT NULL,
  player_id    BIGINT  NOT NULL REFERENCES player(id) ON DELETE CASCADE ON UPDATE CASCADE,
  time_ms      INTEGER NOT NULL,
  pieces       INTEGER NOT NULL DEFAULT 0,
  route_units  INTEGER NOT NULL DEFAULT 0,
  version_id   BIGINT REFERENCES version(id) ON DELETE SET NULL ON UPDATE CASCADE,
  server_id    BIGINT REFERENCES server(id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at   BIGINT  NOT NULL,
  CONSTRAINT random_run_time_positive CHECK (time_ms > 0),
  CONSTRAINT random_run_seed_positive CHECK (seed > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS random_run_seed_player
  ON random_run (seed, player_id);
-- The board: fastest first within a seed, and newest seeds first overall.
CREATE INDEX IF NOT EXISTS random_run_seed_time ON random_run (seed, time_ms);
CREATE INDEX IF NOT EXISTS random_run_created   ON random_run (created_at DESC);
CREATE INDEX IF NOT EXISTS random_run_player    ON random_run (player_id);

-- Down Migration
DROP TABLE IF EXISTS random_run;
