-- Map review flags + the admin account/session system that gates their review.
--
-- Two features land together because the admin surface exists to triage flags:
--
--   * map_flag      — a public "flag this map for review" report (broken,
--                     offensive, wrong metadata, duplicate, …). Anonymous and
--                     rate-limited at the HTTP layer; deduped per reporter so a
--                     refresh-spammer can't inflate a map's count. reporter_hash
--                     is a salted SHA-256 of the client IP (never the raw IP),
--                     kept only for that dedupe and light abuse triage.
--
--   * admin_user    — a moderator login (username + scrypt password hash). There
--                     is no public sign-up; accounts are created out-of-band with
--                     `node admin.js admin-add`. The admin area is unlinked from
--                     the site and lives behind these credentials.
--
--   * admin_session — server-side session store. The browser holds only an
--                     opaque random cookie value; the DB stores its SHA-256 hash
--                     (so a DB read can't reconstruct a live cookie), an absolute
--                     expiry, and a per-session CSRF token for the form POSTs.
--
-- Timestamps are UNIX seconds (BIGINT), matching every other table here.

-- Up Migration
CREATE TABLE IF NOT EXISTS map_flag (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_id        BIGINT NOT NULL REFERENCES map(id) ON DELETE CASCADE ON UPDATE CASCADE,
  reason        TEXT NOT NULL,                    -- broken|offensive|wrong_name|duplicate|other
  note          TEXT,                             -- optional free text, capped at the HTTP layer
  status        TEXT NOT NULL DEFAULT 'open',     -- open|resolved|dismissed
  reporter_hash TEXT,                             -- dedupe key: salted SHA-256 of the reporter IP (web) or player identity (in-game)
  reporter_name TEXT,                             -- display name of the in-game reporter (/flag); NULL for anonymous web reports
  created_at    BIGINT NOT NULL,
  resolved_at   BIGINT,
  resolved_by   TEXT                              -- admin username or "cli"
);
CREATE INDEX IF NOT EXISTS idx_map_flag_status ON map_flag(status);
CREATE INDEX IF NOT EXISTS idx_map_flag_map    ON map_flag(map_id);
-- One OPEN flag per (map, reason, reporter): a partial unique index so the same
-- reporter re-flagging the same map for the same reason is a no-op (ON CONFLICT
-- DO NOTHING), while distinct reporters/reasons still accrue as separate rows.
-- Resolved/dismissed rows are outside the predicate, so a map can be flagged
-- again after a prior report was closed.
CREATE UNIQUE INDEX IF NOT EXISTS uq_map_flag_open
  ON map_flag(map_id, reason, reporter_hash) WHERE status = 'open';

CREATE TABLE IF NOT EXISTS admin_user (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,                    -- "scrypt$<saltHex>$<hashHex>"
  created_at    BIGINT NOT NULL,
  last_login_at BIGINT
);

CREATE TABLE IF NOT EXISTS admin_session (
  token_hash TEXT PRIMARY KEY,                    -- SHA-256 of the opaque cookie value
  admin_id   BIGINT NOT NULL REFERENCES admin_user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  csrf       TEXT NOT NULL,                       -- per-session token echoed in form POSTs
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  ip         TEXT,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS idx_admin_session_admin   ON admin_session(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_session_expires ON admin_session(expires_at);

-- Down Migration
DROP TABLE IF EXISTS admin_session CASCADE;
DROP TABLE IF EXISTS admin_user CASCADE;
DROP TABLE IF EXISTS map_flag CASCADE;
