-- Machine-owned quarantine for maps that kill a game server on load.
--
-- WHY A SEPARATE TABLE FROM map_block. map_block's own migration states the
-- invariant in as many words (20260716130000000_map_block.sql): "a single flag
-- must never auto-remove a map (abuse), so removal is an explicit moderator
-- action". That invariant is right and is NOT overturned here. This is a
-- distinct, machine-owned, auto-expiring, one-click-reversible table that
-- happens to share the same delivery channel (GET /api/game/blocked-maps), so
-- the moderator's list is never polluted by the machine's.
--
-- WHY KEYED BY NAME, NOT map_id. A map that crashes on load has by definition
-- never been finished, so it usually has no `map` row at all. Keying on the
-- name is what lets a node report a map the central database has never heard
-- of. A `map` row is created lazily, only when a quarantine actually
-- activates, so a single transient failure never mints one.
--
-- WHAT IT BUYS. Today a bad map is discovered independently by each node, over
-- and over, because nothing is shared. Once a quarantine activates, the name
-- joins the blocked-maps feed and BOTH already-deployed consumers act on it
-- with no game deploy: server/entrypoint.sh subtracts it from INSTALLED at boot
-- (removing it from g_maplist, rs_idle_pool AND the boot map in one place), and
-- hrace/blockedmaps.as re-fetches every ~30s so the vote and rotation paths
-- drop it within one interval. One node's crash protects the other three.

-- Up Migration

-- Evidence. One row per (server, map, failure); the UNIQUE key is what lets
-- several reporters describe the same event without inflating the counters.
CREATE TABLE IF NOT EXISTS map_load_failure (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_name    TEXT   NOT NULL,
  server_id   BIGINT REFERENCES server(id) ON DELETE SET NULL ON UPDATE CASCADE,
  detected_at BIGINT NOT NULL,
  detector    TEXT,                      -- crashguard|mod|admin
  note        TEXT,                      -- captured ERROR: banner + exit code
  UNIQUE (server_id, map_name, detected_at)
);
CREATE INDEX IF NOT EXISTS map_load_failure_name_idx ON map_load_failure(map_name);

-- The decision. fail_count is total reports; server_count is how many DISTINCT
-- nodes have seen it, which is the signal that separates "this map is broken"
-- from "one box has a corrupt pk3".
CREATE TABLE IF NOT EXISTS map_quarantine (
  map_name        TEXT PRIMARY KEY,
  fail_count      INT     NOT NULL DEFAULT 0,
  server_count    INT     NOT NULL DEFAULT 0,
  first_failed_at BIGINT  NOT NULL,
  last_failed_at  BIGINT  NOT NULL,
  last_server_id  BIGINT REFERENCES server(id) ON DELETE SET NULL ON UPDATE CASCADE,
  last_note       TEXT,
  active          BOOLEAN NOT NULL DEFAULT FALSE,
  -- NULL = never expires. Set to now+7d while the evidence is thin so a map
  -- broken by a transient local condition (a half-written pk3 mid-rsync) comes
  -- back on its own, and cleared to NULL once it is unambiguous.
  expires_at      BIGINT,
  cleared_by      TEXT,
  cleared_at      BIGINT
);
CREATE INDEX IF NOT EXISTS map_quarantine_active_idx ON map_quarantine(active, expires_at);

-- Down Migration
DROP TABLE IF EXISTS map_load_failure;
DROP TABLE IF EXISTS map_quarantine;
