-- Baseline migration — the schema as it stood under the old hand-rolled
-- bootstrapSchema() (former SCHEMA_VERSION 5). Every statement is IF NOT EXISTS
-- so this is a safe no-op on the already-populated production database: it
-- changes nothing there but records the baseline as applied in `pgmigrations`,
-- which is how node-pg-migrate is adopted on an existing DB without a manual
-- fake-apply. On a fresh database (tests, new deploys) it builds everything.
--
-- The 17-digit UTC filename prefix (YYYYMMDDHHMMSSmmm) is node-pg-migrate's
-- `utc` format, so files sort chronologically and the baseline always precedes
-- future migrations. Author new ones with:  npm run migrate:create <name>

-- Up Migration
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS config (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS version (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS map (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS player (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  simplified   TEXT NOT NULL,
  trimmed      TEXT NOT NULL,
  login        TEXT NOT NULL,
  canonical_id BIGINT,
  UNIQUE( name, login )
);
CREATE TABLE IF NOT EXISTS canonical (
  key       TEXT PRIMARY KEY,
  player_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS server (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  token_hash   TEXT UNIQUE,
  status       TEXT NOT NULL DEFAULT 'trusted',  -- trusted|quarantined|revoked
  created_at   BIGINT NOT NULL,
  last_seen_at BIGINT,
  records      BIGINT NOT NULL DEFAULT 0,
  address      TEXT
);
CREATE TABLE IF NOT EXISTS race (
  id           BIGINT PRIMARY KEY,  -- app-allocated monotonic counter
  version_id   BIGINT NOT NULL,
  player_id    BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE ON UPDATE CASCADE,
  map_id       BIGINT NOT NULL REFERENCES map(id) ON DELETE CASCADE ON UPDATE CASCADE,
  time         INTEGER NOT NULL,
  version_rank INTEGER NOT NULL DEFAULT 99999,
  global_rank  INTEGER NOT NULL DEFAULT 99999,
  server_id    BIGINT,
  created_at   BIGINT,
  UNIQUE( player_id, map_id, version_id )
);
CREATE TABLE IF NOT EXISTS checkpoint (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id BIGINT NOT NULL REFERENCES race(id) ON DELETE CASCADE ON UPDATE CASCADE,
  number  INTEGER NOT NULL,
  time    INTEGER NOT NULL,
  UNIQUE( race_id, number )
);
CREATE TABLE IF NOT EXISTS run_tally (
  player_id   BIGINT NOT NULL,
  map_id      BIGINT NOT NULL,
  version_id  BIGINT NOT NULL,
  finishes    BIGINT NOT NULL DEFAULT 0,
  attempts    BIGINT NOT NULL DEFAULT 0,
  last_finish BIGINT,
  PRIMARY KEY (player_id, map_id, version_id)
);

CREATE INDEX IF NOT EXISTS idx_race_map       ON race(map_id);
CREATE INDEX IF NOT EXISTS idx_race_player    ON race(player_id);
CREATE INDEX IF NOT EXISTS idx_race_map_time  ON race(map_id, time);
CREATE INDEX IF NOT EXISTS idx_race_created   ON race(created_at DESC) WHERE created_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cp_race        ON checkpoint(race_id);
CREATE INDEX IF NOT EXISTS idx_tally_map      ON run_tally(map_id);
CREATE INDEX IF NOT EXISTS idx_player_canonical ON player(canonical_id);

-- Search: trigram GIN indexes make ILIKE '%q%' and % (similarity) fast and
-- typo-tolerant, replacing the SQLite layer's full-table LIKE scans.
CREATE INDEX IF NOT EXISTS idx_player_simplified_trgm ON player USING gin (simplified gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_player_name_trgm       ON player USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_player_trimmed_trgm    ON player USING gin (trimmed gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_map_name_trgm          ON map USING gin (name gin_trgm_ops);

-- The monotonic race-id counter the app allocates from (see RaceDB). The
-- former schema_version row is intentionally gone: node-pg-migrate's
-- pgmigrations table is the source of truth for schema version now.
INSERT INTO config (key, value) VALUES ('next_race_id', '1')
  ON CONFLICT (key) DO NOTHING;

-- Down Migration
-- Full teardown of the baseline. Deliberately leaves the pg_trgm extension in
-- place (dropping a shared extension is more destructive than a table drop).
DROP TABLE IF EXISTS checkpoint CASCADE;
DROP TABLE IF EXISTS run_tally CASCADE;
DROP TABLE IF EXISTS race CASCADE;
DROP TABLE IF EXISTS canonical CASCADE;
DROP TABLE IF EXISTS server CASCADE;
DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS map CASCADE;
DROP TABLE IF EXISTS version CASCADE;
DROP TABLE IF EXISTS config CASCADE;
