-- Full finish log: one row per completed run, not just each player's PB (which
-- stays in `race`). The game reports every finish via /api/ingest (source
-- racelog); previously a non-PB finish only bumped run_tally.finishes and was
-- otherwise dropped. This keeps the whole history — every run and its splits —
-- so profiles/maps can show all finishes and a global recent-finishes feed.
-- Attempts remain aggregate counts (run_tally): the game reports attempt COUNTS,
-- not individual attempt events, so there is nothing per-attempt to log.

-- Up Migration
CREATE TABLE IF NOT EXISTS finish (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id  BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE ON UPDATE CASCADE,
  map_id     BIGINT NOT NULL REFERENCES map(id) ON DELETE CASCADE ON UPDATE CASCADE,
  version_id BIGINT NOT NULL,
  time       INTEGER NOT NULL,
  server_id  BIGINT,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_finish_map_time       ON finish(map_id, time);
CREATE INDEX IF NOT EXISTS idx_finish_player_recent  ON finish(player_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_finish_recent         ON finish(created_at DESC);

CREATE TABLE IF NOT EXISTS finish_checkpoint (
  finish_id BIGINT NOT NULL REFERENCES finish(id) ON DELETE CASCADE ON UPDATE CASCADE,
  number    INTEGER NOT NULL,
  time      INTEGER NOT NULL,
  UNIQUE (finish_id, number)
);

-- Down Migration
DROP TABLE IF EXISTS finish_checkpoint CASCADE;
DROP TABLE IF EXISTS finish CASCADE;
