-- 1v1 duels: the concluded head-to-head match-ups reported by the game servers
-- (hrace/duel.as -> RS_ApiReportDuel -> POST /api/game/duel), shown as a
-- match-up card on both players' profiles.
--
-- One row per FINISHED duel. A duel that is still running lives only in the
-- game server's memory: it has no result yet, it cannot outlive the map it is
-- being raced on, and a half-written row on two profiles would be worse than no
-- row at all. So nothing is written here until the game has decided a winner.
--
-- Design notes worth keeping next to the schema:
--
--   * player_a / player_b are the CANONICAL representative ids at insert time,
--     the same convention as tournament_entrant. Reads must map stored ids
--     through canonical_id (in both directions) rather than comparing them
--     raw, because a canonical rebuild can pick a new representative for an
--     alias group and the stored id then no longer equals what the nick
--     resolves to.
--
--   * winner_id is NULL for a draw. It is stored rather than derived from the
--     two times because a FORFEIT is a loss regardless of who was faster —
--     the times alone cannot express the result.
--
--   * time_a / time_b are NULL when that player never finished the map inside
--     the duel, which is a real and common outcome. NULL, not 0: a 0 would sort
--     as the fastest run ever recorded.
--
--   * map_id points at the map the duel was raced on, INCLUDING the reversed
--     variant — a reverse duel carries the "<map>-reversed" map row, exactly
--     like a reverse finish does. Nothing here needs a separate direction flag.

-- Up Migration
CREATE TABLE IF NOT EXISTS duel (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  map_id      BIGINT NOT NULL REFERENCES map(id) ON DELETE CASCADE ON UPDATE CASCADE,
  player_a    BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE ON UPDATE CASCADE,
  player_b    BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE ON UPDATE CASCADE,
  time_a      INTEGER,
  time_b      INTEGER,
  finishes_a  INTEGER NOT NULL DEFAULT 0,
  finishes_b  INTEGER NOT NULL DEFAULT 0,
  winner_id   BIGINT REFERENCES player(id) ON DELETE SET NULL ON UPDATE CASCADE,
  reason      TEXT   NOT NULL DEFAULT 'map_change',  -- map_change|disconnect|forfeit
  duration    INTEGER NOT NULL DEFAULT 0,            -- seconds the duel ran
  version_id  BIGINT REFERENCES version(id) ON DELETE SET NULL ON UPDATE CASCADE,
  server_id   BIGINT,
  created_at  BIGINT NOT NULL
);

-- The profile card is "this player's duels, newest first", and a player is on
-- either side of the pair, so both directions need their own index.
CREATE INDEX IF NOT EXISTS duel_a_idx ON duel ( player_a, created_at DESC );
CREATE INDEX IF NOT EXISTS duel_b_idx ON duel ( player_b, created_at DESC );
CREATE INDEX IF NOT EXISTS duel_map_idx ON duel ( map_id, created_at DESC );

-- Down Migration
DROP TABLE IF EXISTS duel;
