"""Greybox textures, skybox and shaders, generated — no binary blobs in git.

Everything lives under a versioned name (mapgen_v1) and ships INSIDE each
generated .pk3, so a map is self-contained: a client that downloads it gets
the look with it. Two generated maps carry byte-identical copies, and the
engine resolves the duplicate shader names to the same thing. If the look
ever changes, bump the version rather than editing v1 in place — otherwise
two installed maps would disagree about what mapgen_v1/floor means and load
order would pick one.
"""

import struct

VERSION = "mapgen_v1"
SIZE = 128
GRID = 32   # px; with mapfile.TEX_SCALE 2 that is a 64-unit grid in game

# (base RGB, line RGB) per texture.
PALETTE = {
    "floor": ((138, 143, 152), (104, 108, 116)),
    "wall": ((92, 104, 122), (70, 80, 96)),
    "start": ((63, 174, 90), (40, 128, 62)),
    "finish": ((208, 70, 60), (150, 44, 38)),
    "checkpoint": ((232, 185, 35), (180, 140, 20)),
    "edge": ((232, 185, 35), (40, 40, 40)),
}

SHADER = f"""// generated by tools/mapgen/assets.py
textures/{VERSION}/sky
{{
	qer_editorimage env/{VERSION}/sky_up.tga
	surfaceparm sky
	surfaceparm noimpact
	surfaceparm nolightmap
	surfaceparm nomarks
	q3map_sun 1 0.97 0.9 140 35 55
	q3map_skylight 90 3
	skyparms env/{VERSION}/sky - -
}}

textures/{VERSION}/trigger
{{
	qer_trans 0.4
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans
}}
"""


def tga(width, height, pixel):
    """Uncompressed 24-bit TGA, bottom-up rows (the format's default origin)."""
    header = struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, width, height, 24, 0)
    rows = bytearray()
    for y in range(height):
        for x in range(width):
            r, g, b = pixel(x, y)
            rows += bytes((b, g, r))
    return header + bytes(rows)


def grid_texture(kind):
    base, line = PALETTE[kind]

    def pixel(x, y):
        if kind == "edge":
            # Diagonal hazard stripes for gap lips.
            return base if ((x + y) // 16) % 2 == 0 else line
        if kind == "finish" and ((x // GRID) + (y // GRID)) % 2:
            return line
        on_edge = x % GRID in (0, GRID - 1) or y % GRID in (0, GRID - 1)
        on_major = x in (0, SIZE - 1) or y in (0, SIZE - 1)
        if on_major:
            return tuple(max(0, c - 20) for c in line)
        return line if on_edge else base

    return tga(SIZE, SIZE, pixel)


def sky_face(face):
    """A plain vertical gradient; the up face is the zenith colour."""
    top, horizon = (74, 122, 186), (186, 208, 230)
    n = 64

    def pixel(x, y):
        if face == "up":
            return top
        if face == "dn":
            return (60, 64, 72)
        t = y / (n - 1)   # TGA rows are bottom-up: y=0 is the horizon edge
        return tuple(int(h + (tp - h) * t) for h, tp in zip(horizon, top))

    return tga(n, n, pixel)


def files():
    """{path inside the pk3 / basepath: bytes}"""
    out = {f"scripts/{VERSION}.shader": SHADER.encode()}
    for kind in PALETTE:
        out[f"textures/{VERSION}/{kind}.tga"] = grid_texture(kind)
    for face in ("rt", "lf", "ft", "bk", "up", "dn"):
        out[f"env/{VERSION}/sky_{face}.tga"] = sky_face(face)
    return out
