"""Racesow dev textures, skybox and shaders, generated: no binary blobs in git.

The look borrows the site's palette (web/public/assets/css: --orange #ff6a1a,
--cyan #22d3ee, --green #a9f26a on navy) and the conventions of a dev
texture set. Every surface carries a measuring grid, because a racer reads
distances off the floor:

    floor       light grey, 64-unit cells, 16-unit sub-grid, unit labels
    wall        dark slate, the same grid; clearly darker than any floor
    start       navy pad, green chevrons pointing down the course, "START"
    finish      black / white checker with an orange "FINISH" band
    checkpoint  cyan line strip with "CP" markers
    edge        orange / black hazard stripes on every gap lip
    trim        orange racing stripe on the start and finish lines
    pylon       slalom and split fins: navy with cyan bands, "go round me"
    kick        wall-jump walls: yellow chevrons pointing up on navy, "kick off me"
    ice         slick floor: pale ice blue, the same grid, frost glints, "ICE";
                its shader carries surfaceparm slick (no ground friction)

Textures are 256 px and mapfile.TEX_SCALE is 1, so 1 px = 1 game unit and
the grid is true to scale.

Everything lives under a versioned name (mapgen_v1) and ships INSIDE each
generated .pk3, so a map is self-contained: a client that downloads it gets
the look with it. Two generated maps carry byte-identical copies, and the
engine resolves the duplicate shader names to the same thing. Once a map
using a version is published, never edit that version in place: bump it.
Otherwise two installed maps would disagree about what mapgen_v1/floor means
and load order would pick one. (v1 is still unpublished.)
"""

import struct

VERSION = "mapgen_v1"
SIZE = 256

ORANGE = (255, 106, 26)
ORANGE_DIM = (193, 78, 16)
CYAN = (34, 211, 238)
GREEN = (169, 242, 106)
NAVY = (21, 24, 36)
NAVY_2 = (38, 43, 61)
WHITE = (232, 235, 245)
YELLOW = (250, 204, 21)
BLACK = (18, 19, 24)

SHADER = f"""// generated by tools/mapgen/assets.py
textures/{VERSION}/sky
{{
	qer_editorimage env/{VERSION}/sky_up.tga
	surfaceparm sky
	surfaceparm noimpact
	surfaceparm nolightmap
	surfaceparm nomarks
	q3map_sun 1 0.97 0.9 25 35 55
	q3map_skylight 30 3
	skyparms env/{VERSION}/sky - -
}}

textures/{VERSION}/trigger
{{
	qer_trans 0.4
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans
}}

// An origin brush: the ONLY thing that gives a brush entity its own coordinate
// frame. q3map2 takes the centre of a brush wearing this shader as the
// entity's origin, subtracts it from the entity's other brushes and drops the
// brush itself, so the compiled inline model is expressed around that point.
// An "origin" KEY does not do this — measured, not assumed: a key alone leaves
// the submodel at its world position, which puts a dealt tile wherever it
// happened to be compiled instead of where it is placed. Setting both is worse
// than either, because q3map2 ADDS the key to the brush-derived origin.
// Used by tiles.py; a written course has no brush entity that needs a frame.
textures/{VERSION}/origin
{{
	qer_trans 0.3
	surfaceparm origin
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans
}}
"""

# Ice has its own shader file rather than an entry in SHADER above. Packs
# already in the map store carry scripts/mapgen_v1.shader WITHOUT it, and when
# two packs hold the same path the engine reads only one of them, so an ice
# entry added there could be shadowed by an older pack. A file name no
# published pack has cannot be. It ships only in packs whose course uses ice
# (files(ice=True)), so a course without ice packs the same bytes as before.
#
# surfaceparm slick is a COMPILE-time property: q3map2 writes SURF_SLICK into
# the bsp's shaderref flags, and that is what the engine's movement code and
# the site's slick scan (web/bsp.js parseSlick) read. build.check_bsp confirms
# it survived compilation.
ICE_SHADER_PATH = f"scripts/{VERSION}_ice.shader"
ICE_SHADER = f"""// generated by tools/mapgen/assets.py
textures/{VERSION}/ice
{{
	qer_editorimage textures/{VERSION}/ice.tga
	surfaceparm slick
	{{
		map $lightmap
		rgbGen identity
	}}
	{{
		map textures/{VERSION}/ice.tga
		blendFunc filter
	}}
}}
"""

# 5x7 bitmap font, only the glyphs the textures use. Rows top to bottom.
FONT = {
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "3": ["11110", "00001", "00001", "01110", "00001", "00001", "11110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
    "6": ["00110", "01000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00010", "01100"],
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "C": ["01110", "10001", "10000", "10000", "10000", "10001", "01110"],
    "E": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "F": ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    "H": ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    "I": ["01110", "00100", "00100", "00100", "00100", "00100", "01110"],
    "N": ["10001", "11001", "10101", "10011", "10001", "10001", "10001"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "P": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "W": ["10001", "10001", "10001", "10101", "10101", "10101", "01010"],
    " ": ["00000"] * 7,
}


class Canvas:
    """RGB raster, y down (like an image editor); tga() flips on write."""

    def __init__(self, size, fill):
        self.n = size
        self.px = [list(fill) for _ in range(size * size)]

    def set(self, x, y, c):
        if 0 <= x < self.n and 0 <= y < self.n:
            self.px[y * self.n + x] = list(c)

    def rect(self, x0, y0, x1, y1, c):
        for y in range(max(0, y0), min(self.n, y1)):
            row = y * self.n
            for x in range(max(0, x0), min(self.n, x1)):
                self.px[row + x] = list(c)

    def grid(self, step, width, c, offset=0):
        for i in range(offset, self.n, step):
            self.rect(i, 0, i + width, self.n, c)
            self.rect(0, i, self.n, i + width, c)

    def text(self, x, y, s, scale, c):
        for ch in s:
            glyph = FONT[ch]
            for gy, row in enumerate(glyph):
                for gx, bit in enumerate(row):
                    if bit == "1":
                        self.rect(x + gx * scale, y + gy * scale,
                                  x + (gx + 1) * scale, y + (gy + 1) * scale, c)
            x += 6 * scale

    @staticmethod
    def text_width(s, scale):
        return (6 * len(s) - 1) * scale

    def tga(self):
        """Uncompressed 24-bit TGA, bottom-up rows (the format's default)."""
        header = struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, self.n, self.n, 24, 0)
        out = bytearray(header)
        for y in range(self.n - 1, -1, -1):
            for r, g, b in self.px[y * self.n:(y + 1) * self.n]:
                out += bytes((b, g, r))
        return bytes(out)


def _shade(c, d):
    return tuple(max(0, min(255, v + d)) for v in c)


def _dev_grid(base, labels=True, label_color=None):
    """The shared dev-texture grid: 16-unit sub-grid, 64-unit cells, and a
    heavier line on the 256 tile edge, each unit label in its cell corner."""
    c = Canvas(SIZE, base)
    c.grid(16, 1, _shade(base, -10))
    c.grid(64, 2, _shade(base, -26))
    c.rect(0, 0, SIZE, 3, _shade(base, -40))
    c.rect(0, 0, 3, SIZE, _shade(base, -40))
    if labels:
        lc = label_color or _shade(base, -34)
        for i, lab in enumerate(("64", "128", "192")):
            c.text(6 + 64 * (i + 1), 6, lab, 1, lc)
            c.text(6, 6 + 64 * (i + 1), lab, 1, lc)
    return c


def floor():
    c = _dev_grid((136, 140, 151))
    # One orange corner tick per tile: the racesow accent, and a cue for
    # where a 256-unit tile starts.
    c.rect(3, 3, 19, 6, ORANGE)
    c.rect(3, 3, 6, 19, ORANGE)
    return c


def wall():
    # Walls are deliberately much darker than any floor, so the walking
    # surface reads at a glance.
    c = _dev_grid((64, 69, 82), label_color=(92, 98, 114))
    # A thin orange pinstripe and the wordmark under it. Wall surfaces
    # project world Z, so they recur every 256 units of height.
    c.rect(0, 226, SIZE, 229, ORANGE_DIM)
    c.text(8, 236, "RACESOW", 2, ORANGE_DIM)
    return c


def start():
    c = _dev_grid(NAVY, labels=False)
    # Chevrons point toward the top of the texture, which mapfile rotates to
    # face down the course. Each arm is a 6 px thick diagonal meeting at the tip.
    for tip in (22, 182):
        for i in range(30):
            for w in range(7):
                c.set(128 - i, tip + i + w, GREEN)
                c.set(128 + i, tip + i + w, GREEN)
    s = "START"
    c.text((SIZE - Canvas.text_width(s, 5)) // 2, 108, s, 5, GREEN)
    return c


def finish():
    c = Canvas(SIZE, WHITE)
    for y in range(0, SIZE, 32):
        for x in range(0, SIZE, 32):
            if (x // 32 + y // 32) % 2:
                c.rect(x, y, x + 32, y + 32, BLACK)
    c.rect(0, 96, SIZE, 160, ORANGE)
    s = "FINISH"
    c.text((SIZE - Canvas.text_width(s, 5)) // 2, 111, s, 5, BLACK)
    return c


def checkpoint():
    c = Canvas(SIZE, NAVY_2)
    c.rect(0, 0, SIZE, 6, CYAN)
    c.rect(0, SIZE - 6, SIZE, SIZE, CYAN)
    for x in range(0, SIZE, 128):
        c.text(x + 40, 100, "CP", 6, CYAN)
    return c


def edge():
    c = Canvas(SIZE, BLACK)
    for y in range(SIZE):
        for x in range(SIZE):
            if ((x + y) // 32) % 2 == 0:
                c.set(x, y, ORANGE)
    return c


def trim():
    c = Canvas(SIZE, ORANGE)
    c.rect(0, 0, SIZE, 8, WHITE)
    c.rect(0, SIZE - 8, SIZE, SIZE, WHITE)
    return c


def pylon():
    # Obstacles to steer round, not edges to fear: cyan (the checkpoint
    # colour) rather than the orange hazard stripes that mark a fall. Bands
    # run vertically on a wall face, so a fin reads as a post from any angle.
    c = Canvas(SIZE, NAVY_2)
    for x in range(0, SIZE, 64):
        c.rect(x + 8, 0, x + 40, SIZE, CYAN)
    c.rect(0, 0, SIZE, 6, WHITE)
    c.rect(0, SIZE - 6, SIZE, SIZE, WHITE)
    return c


def kick():
    # Walls to wall-jump off: a colour used nowhere else (orange means a fall,
    # cyan an obstacle), with chevrons pointing up, the way the kick sends you.
    c = Canvas(SIZE, NAVY_2)
    for y0 in range(0, SIZE, 64):   # one chevron per 64 units, apex at the top
        for k in range(24):
            y = y0 + 20 + k
            w = k * 3
            c.rect(128 - w - 12, y, 128 - w, y + 1, YELLOW)
            c.rect(128 + w, y, 128 + w + 12, y + 1, YELLOW)
    c.rect(0, 0, 6, SIZE, YELLOW)
    c.rect(SIZE - 6, 0, SIZE, SIZE, YELLOW)
    return c


def ice():
    # Same grid as the floor, so distances still read, on a pale ice blue
    # that no other walking surface uses. Frost glints run diagonally so the
    # floor looks glassy at speed, and a cyan corner tick (instead of the
    # floor's orange) says "different surface" from a distance.
    base = (172, 214, 232)
    c = _dev_grid(base, label_color=(120, 168, 190))
    frost = (226, 244, 252)
    for x0, y0, n in ((40, 70, 46), (150, 30, 30), (176, 150, 54), (60, 190, 26), (110, 120, 18)):
        for i in range(n):
            c.rect(x0 + i, y0 - i, x0 + i + 2, y0 - i + 1, frost)
    c.rect(3, 3, 19, 6, CYAN)
    c.rect(3, 3, 6, 19, CYAN)
    s = "ICE"
    c.text((SIZE - Canvas.text_width(s, 4)) // 2, 210, s, 4, (140, 190, 212))
    return c


def hazard():
    """Lethal floor: hot rock, dark crust broken by a glowing fracture grid.
    It reads as "do not land here" at a glance and from any height, which is
    the whole job — a hazard a player cannot see is just an unfair gap."""
    crust, glow, hot = (38, 14, 10), (196, 72, 18), (252, 186, 64)
    c = Canvas(SIZE, crust)
    # A coarse cell grid with the glow in the cracks between the plates.
    cell = SIZE // 4
    for i in range(0, SIZE, cell):
        c.rect(i - 3, 0, i + 3, SIZE, glow)
        c.rect(0, i - 3, SIZE, i + 3, glow)
    # Plates: a slightly lighter crust inset in each cell, so the cracks read
    # as depth rather than as paint.
    for gx in range(4):
        for gy in range(4):
            x0, y0 = gx * cell + 6, gy * cell + 6
            shade = tuple(min(255, v + 10 + 6 * ((gx + gy) % 3)) for v in crust)
            c.rect(x0, y0, x0 + cell - 12, y0 + cell - 12, shade)
    # The hottest light pools where the cracks meet.
    for i in range(0, SIZE, cell):
        for j in range(0, SIZE, cell):
            c.rect(i - 5, j - 5, i + 5, j + 5, hot)
    # The stencil font is the one in this file: 0-9 and A C E F H I N O P R S T W.
    s = "HOT"
    c.text((SIZE - Canvas.text_width(s, 4)) // 2, 210, s, 4, hot)
    return c


TEXTURES = {
    "floor": floor, "wall": wall, "start": start, "finish": finish,
    "checkpoint": checkpoint, "edge": edge, "trim": trim, "pylon": pylon, "kick": kick,
    "hazard": hazard,
}
# Shipped only with a course that uses them (files(ice=True)); see ICE_SHADER.
ICE_TEXTURES = {"ice": ice}


def sky_face(face):
    """Dusk gradient: navy at the zenith into a warm orange horizon."""
    n = 64
    top, horizon = (16, 20, 38), (190, 96, 52)
    c = Canvas(n, top)
    if face == "dn":
        c.rect(0, 0, n, n, NAVY)
    elif face != "up":
        for y in range(n):
            t = (y / (n - 1)) ** 1.6
            c.rect(0, y, n, y + 1, tuple(int(a + (b - a) * t) for a, b in zip(top, horizon)))
    return c.tga()


def files(ice=False):
    """{path inside the pk3 / basepath: bytes}. ice=True adds the ice texture
    and its shader file, for a course with an icy piece."""
    out = {f"scripts/{VERSION}.shader": SHADER.encode()}
    for kind, make in TEXTURES.items():
        out[f"textures/{VERSION}/{kind}.tga"] = make().tga()
    if ice:
        out[ICE_SHADER_PATH] = ICE_SHADER.encode()
        for kind, make in ICE_TEXTURES.items():
            out[f"textures/{VERSION}/{kind}.tga"] = make().tga()
    for face in ("rt", "lf", "ft", "bk", "up", "dn"):
        out[f"env/{VERSION}/sky_{face}.tga"] = sky_face(face)
    return out
