"""Course -> Quake 3 .map text, the input q3map2 compiles.

Each Prism becomes one brush: a bottom face, a top face and one side face per
footprint edge. A face is written as three points on its plane. q3map2 derives
the plane normal as cross(p2 - p0, p1 - p0) (tools/quake3/common/qmath.h,
PlaneFromPoints) and every brush face must point OUT of the brush, so
_face() orders the points to match the outward normal we already know
instead of relying on a winding convention.
"""

import layout

TEX_SCALE = 2.0   # 128 px textures tile every 256 units; grid lines every 64


def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _fmt(v):
    r = round(v, 3)
    if r == int(r):
        return str(int(r))
    return f"{r:.3f}".rstrip("0")


def _face(p0, p1, p2, outward, tex):
    n = _cross(_sub(p2, p0), _sub(p1, p0))
    if _dot(n, outward) < 0:
        p1, p2 = p2, p1
    pts = " ".join("( " + " ".join(_fmt(c) for c in p) + " )" for p in (p0, p1, p2))
    return f"{pts} {tex} 0 0 0 {TEX_SCALE} {TEX_SCALE} 0 0 0"


def brush_lines(prism):
    tex = layout.TEX[prism.tex]
    # Side faces of a floor/sloped piece use the wall texture; only the walking
    # surface carries the floor/start/finish colour.
    side_tex = layout.TEX["wall"] if prism.tex in ("floor", "start", "finish", "edge") else tex
    poly = prism.poly
    n = len(poly)
    top = [(x, y, prism.top_at(x, y)) for x, y in poly]
    bot = [(x, y, prism.zmin) for x, y in poly]
    faces = [
        _face(bot[0], bot[1], bot[2], (0, 0, -1), side_tex),
        _face(top[0], top[1], top[2], (0, 0, 1), tex),
    ]
    for i in range(n):
        a, b = poly[i], poly[(i + 1) % n]
        # CCW footprint: the outward normal of edge a->b is (dy, -dx).
        out = (b[1] - a[1], -(b[0] - a[0]), 0)
        faces.append(_face(bot[i], bot[(i + 1) % n], top[i], out, side_tex))
    return ["{"] + faces + ["}"]


def _kv(k, v):
    if isinstance(v, tuple):
        v = " ".join(_fmt(c) for c in v)
    elif isinstance(v, float):
        v = _fmt(v)
    return f'"{k}" "{v}"'


def write(course):
    spec = course.spec
    out = ["// generated by tools/mapgen — edit the spec, not this file", "{",
           _kv("classname", "worldspawn"),
           _kv("message", spec["title"]),
           # Flat greybox lighting: the sky shader carries a sun and skylight;
           # _minlight keeps shadowed corners readable.
           _kv("_minlight", 48),
           _kv("_color", "1 1 1")]
    for b, prism in enumerate(course.world):
        out.append(f"// brush {b}")
        out += brush_lines(prism)
    out.append("}")
    for keys, brushes in course.entities:
        out.append("{")
        out += [_kv(k, v) for k, v in keys.items()]
        for prism in brushes:
            out += brush_lines(prism)
        out.append("}")
    return "\n".join(out) + "\n"
