"""Course -> Quake 3 .map text, the input q3map2 compiles.

Each Prism becomes one brush: a bottom face, a top face and one side face per
footprint edge. A face is written as three points on its plane. q3map2 derives
the plane normal as cross(p2 - p0, p1 - p0) (tools/quake3/common/qmath.h,
PlaneFromPoints) and every brush face must point OUT of the brush, so
_face() orders the points to match the outward normal we already know
instead of relying on a winding convention.
"""

import layout

TEX_SCALE = 1.0   # 256 px textures, 1 px = 1 unit: the dev grid is to scale

# Quake's base texture axes for an upward face are s = +X, t = -Y, so an
# unrotated texture's "up" points along +Y (heading 90). A top face laid at
# `heading` is turned by heading - 90 to put the texture's up down the course.
FLOOR_ROT_OFFSET = -90.0


def _sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _fmt(v):
    r = round(v, 3)
    if r == int(r):
        return str(int(r))
    return f"{r:.3f}".rstrip("0")


def _mirrored(outward):
    """Quake projects a wall texture along the wall's dominant axis with fixed
    s/t axes (s = +Y for X-facing walls, s = +X for Y-facing ones), so on
    walls facing -X or +Y the image reads mirror-image: RACESOW backwards on
    one side of every corridor. Those faces get a negative s scale. Ties go
    to X, matching the order q3map2 tests the base axes in."""
    nx, ny, nz = outward
    if abs(nz) > max(abs(nx), abs(ny)):
        return False
    return nx < 0 if abs(nx) >= abs(ny) else ny > 0


def _face(p0, p1, p2, outward, tex, rot=0.0):
    n = _cross(_sub(p2, p0), _sub(p1, p0))
    if _dot(n, outward) < 0:
        p1, p2 = p2, p1
    pts = " ".join("( " + " ".join(_fmt(c) for c in p) + " )" for p in (p0, p1, p2))
    sx = -TEX_SCALE if _mirrored(outward) else TEX_SCALE
    return f"{pts} {tex} 0 0 {_fmt(rot % 360.0)} {_fmt(sx)} {_fmt(TEX_SCALE)} 0 0 0"


def brush_lines(prism):
    tex = layout.TEX[prism.tex]
    # Side faces of a floor/sloped piece use the wall texture; only the walking
    # surface carries the floor/start/finish colour.
    side_tex = (layout.TEX["wall"]
                if prism.tex in ("floor", "ice", "start", "finish", "edge", "trim", "checkpoint")
                else tex)
    rot = 0.0 if prism.heading is None else prism.heading + FLOOR_ROT_OFFSET
    poly = prism.poly
    n = len(poly)
    # The real corners: a rolled or pitched brush is not its footprint, and
    # a rigid rotation of a convex brush is still a convex brush, so what
    # q3map2 gets here is as valid as the upright version.
    bot, top = prism.corners()
    # The outward hints only orient each face's winding (the plane itself comes
    # from the three points), so they have to turn with the brush.
    turn = (lambda d: d) if prism.tilt is None else (lambda d: layout._rotate(prism.tilt[1], d))
    faces = [
        _face(bot[0], bot[1], bot[2], turn((0, 0, -1)), side_tex),
        _face(top[0], top[1], top[2], turn((0, 0, 1)), tex, rot),
    ]
    for i in range(n):
        a, b = poly[i], poly[(i + 1) % n]
        # CCW footprint: the outward normal of edge a->b is (dy, -dx).
        out = turn((b[1] - a[1], -(b[0] - a[0]), 0))
        faces.append(_face(bot[i], bot[(i + 1) % n], top[i], out, side_tex))
    return ["{"] + faces + ["}"]


# Characters that would end a quoted key or value, or the line, in .map
# syntax. A value holding one could close the entity and open another, so it
# is refused outright rather than escaped: the .map format has no escapes.
_UNSAFE = ('"', "\n", "\r", "\\", "{", "}")


def _kv(k, v):
    if isinstance(v, tuple):
        v = " ".join(_fmt(c) for c in v)
    elif isinstance(v, float):
        v = _fmt(v)
    v = str(v)
    if any(c in str(k) + v for c in _UNSAFE):
        raise ValueError(f"unsafe .map key/value: {k!r} {v!r}")
    return f'"{k}" "{v}"'


def write(course):
    spec = course.spec
    out = ["// generated by tools/mapgen — edit the spec, not this file", "{",
           _kv("classname", "worldspawn"),
           _kv("message", spec["title"]),
           # Flat greybox lighting: the sky shader carries a sun and skylight;
           # _minlight keeps shadowed corners readable.
           _kv("_minlight", 16),
           _kv("_color", "1 1 1")]
    # Anything the layout needs to tell the compiler about the world itself
    # (tiles.py sets _blocksize and _lightgridsize; a course sets nothing).
    for k, v in sorted(getattr(course, "worldspawn", {}).items()):
        out.append(_kv(k, v))
    for b, prism in enumerate(course.world):
        out.append(f"// brush {b}")
        out += brush_lines(prism)
    out.append("}")
    for keys, brushes in course.entities:
        out.append("{")
        out += [_kv(k, v) for k, v in keys.items()]
        for prism in brushes:
            out += brush_lines(prism)
        out.append("}")
    return "\n".join(out) + "\n"
